### ISSUE TITLE
Does this ONLY work with Google Maps?

### ISSUE THREAD

**Issue by ursomniac** [philippbosch/django-geoposition#108]
My client doesn't want to have to pay for every map generated.
Can you update the tutorial for a different service, or if that's impossible with this codebase, any suggestions would be appreciated.

**Comment by philippbosch** [comment]
Yes, this only works with Google Maps atm. 
Happy to accept pull requests for other services.

**Comment by ursomniac** [comment]
Ok.  Thanks for the speedy reply.  I’m hoping I can convince the client otherwise.
