### ISSUE TITLE
Question: is it py3 compatible?

### ISSUE THREAD

**Issue by paulochf** [philippbosch/django-geoposition#41]
I just used [brettcannon/caniusepython3](https://github.com/brettcannon/caniusepython3) to get my project's dependencies which are not Python 3, and django-geoposition happened there. So, I wondered if it it compatible, since nowhere says that.

Thanks!

**Comment by jonashagstedt** [comment]
I'm using it with Py3

**Comment by paulochf** [comment]
The time I asked I was studying migrate my project to Python 3, so I was affraid that I couldn't do it. But it worked and everything is fine since then.
