### ISSUE TITLE
Conflict with jQuery versions

### ISSUE THREAD

**Issue by niceguydave** [philippbosch/django-geoposition#52]
I'm using this package on a project using Django==1.5.12.  The default version of jQuery which comes packaged with this version of Django is 1.4.2

I'm experiencing a problem when viewing the map within the Django admin for an app which throws up the following error:

```Uncaught TypeError: $searchInput.on is not a function  (error occurring in  geoposition.js:102)```

Looking at this line of code, it seems that `$searchInput.on()` doesn't event exist as a callable function when using jQuery==1.4.2 (it *does* in more modern versions of jQuery e.g. 1.7.2).

I can hack things so that I use a more up-to-date version of jQuery just for this file but it would be good if there were a more extendible solution.

**Comment by rstalbow** [comment]
if you added something like this to the ModelAdmin it works: 
```
class Media:
        js = (
            '//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.min.js',
        )
```

**Comment by niceguydave** [comment]
Thanks for the input - appreciated.
