### ISSUE TITLE
Add Google API Key

### ISSUE THREAD

**Issue by rgeber** [philippbosch/django-geoposition#66]
Google has shut down keyless use of the Maps API on June 22nd. This breaks the app. The key should be set in the django settings file(s) and then read by the app.

**Comment by Milutinke92** [comment]
I had a same problem with my app. Is it going to be fixed?

**Comment by LRPalacios** [comment]
Yep, i am on the same boat here, is there any way for fix this at the moment?

**Comment by philippbosch** [comment]
I'm preparing a new release "as we speak". I want to get this out today.

**Comment by LRPalacios** [comment]
@philippbosch thank you, i was checking at the code to be able to define the key in the settings, that great i will wait for it

**Comment by philippbosch** [comment]
I just uploaded v0.2.3 to PyPI which include a new setting `GEOPOSITION_GOOGLE_MAPS_API_KEY`. Please see the README for details. 
Thanks @rgeber for the PR!
