### ISSUE TITLE
inline admin GeoPosition not rendering the map unless you resize the browser window

### ISSUE THREAD

**Issue by imran31415** [philippbosch/django-geoposition#71]
<img width="1105" alt="screen shot 2016-07-23 at 2 37 19 pm" src="https://cloud.githubusercontent.com/assets/2126188/17080412/0a90b548-50e3-11e6-94bd-31e94613a7ea.png">

When I use a geoposition as an inline admin the map does not render until you resize the browser. It just is grey but you can see the red location marker.  It works normally as a stand alone admin component.

Any idea whats causing this?

**Comment by imoran21** [comment]
Happens on both safari and chrome

**Comment by garzdin** [comment]
Any progress on this one?

**Comment by dubsnipe** [comment]
I might be too late to answer this, but the solution is by resizing the map:

`google.maps.event.trigger(map, 'resize')`

However, my JS skills aren't goo enough to have it done.

Reference:
https://developers.google.com/maps/documentation/javascript/reference#Map

**Comment by mohamedAbdElhameed** [comment]
is there a solution for this ?

**Comment by imran31415** [comment]
I would try what dubsnipe suggested and use JavaScript to resize the map as a workaround

**Comment by mohamedAbdElhameed** [comment]
@imran31415 
can you share any snippet of code?
I am trying all the day and get no result

**Comment by imran31415** [comment]
What did you try?

**Comment by mohamedAbdElhameed** [comment]
I was try @dubsnipe solution 
tried add script in form to resize it when new one created

**Comment by imran31415** [comment]
Did you try it exactly as the comment here suggests?  https://stackoverflow.com/questions/42222130/google-maps-shows-gray-screen-instead-of-map

**Comment by imran31415** [comment]
also https://stackoverflow.com/questions/11742839/showing-a-google-map-in-a-modal-created-with-twitter-bootstrap

**Comment by mohamedAbdElhameed** [comment]
```
$("#contact-modal").on("shown.bs.modal", function () {
    google.maps.event.trigger(map, "resize");
});
```
I am keep trying to change contact-model to geoposition-widget and other classes in map widget . 
what is the correct one to add instead of "contact-modal" 
thanks in advance

**Comment by imran31415** [comment]
it should be whatever the ID of your element is in the HTML.  See the HTML of the person asking the question here:

https://stackoverflow.com/questions/11742839/showing-a-google-map-in-a-modal-created-with-twitter-bootstrap

**Comment by mohamedAbdElhameed** [comment]
then what is the id or class name for geo-position widget
```
{% load l10n %}
<div class="geoposition-widget" id="{{widget.attrs.id}}" data-map-widget-height="{{ widget.config.map_widget_height }}" data-map-options='{{ widget.config.map_options }}' data-marker-options='{{ widget.config.marker_options }}'>
    {{ widget.latitude.label|capfirst }}:
    <input type="text" name="{{widget.name}}_0" class="{{widget.attrs.class}}" value="{{ widget.latitude.html|unlocalize }}" />
    {{ widget.longitude.label|capfirst }}:
    <input type="text" name="{{widget.name}}_1" class="{{widget.attrs.class}}" value="{{ widget.longitude.html|unlocalize }}" />
</div>
``` 
this is the html code from the lib it self.
I have tried geoposition-widget as a class name, although there is an id but it changed when creating new inline form model

this issue happens only in Inline admin from to a model with no extra and use add new location to show a new form with the geo-position map widget

this is the big picture of it 
and thanks a lot for your efforts to help me <3

**Comment by Benbb96** [comment]
Hi @mohamedAbdElhameed 

I think you may be interested in using the jQuery event `fomset:added` provided by the Django admin (see https://docs.djangoproject.com/en/3.0/ref/contrib/admin/javascript/)

Something like this should work : 

```javascript
(function($) {
    // Add the show modal event handler after a new row is added
    $(document).on('formset:added', function(event, $row, formsetName) {
        if (formsetName === '[[ name of your manytomany inline field ]]') {
            $row.find('.geoposition-widget').on("shown.bs.modal", function () {
                google.maps.event.trigger(map, "resize");
            });
        }
    });
})(django.jQuery);
```
