### ISSUE TITLE
Map not appear in admin

### ISSUE THREAD

**Issue by davidkrcil** [philippbosch/django-geoposition#87]
I am following your example. In admin area are displayed 2 text fields instead of map widget. What I am doing wrong? Thank you in advance.

After I looked into source. In the admin model edit page I can't find any .geoposition-widget element. which is needed for JQUERY in geoposition.js

Thanks for any help
David

**Comment by davidkrcil** [comment]
It seems Map does not render in version django 1.11. is solution for me

**Comment by andreyshipilov** [comment]
Same here. Django 1.11.8
